"""Advisory export — generates formatted Markdown and HTML documents."""

from __future__ import annotations

from datetime import datetime

from src.models.deal import Deal


class AdvisoryExporter:
    """Exports advisory data into client-ready document formats."""

    def export_markdown(self, deal: Deal, advisory_data: dict) -> str:
        """Generate a formatted Markdown advisory document."""
        lines = [
            f"# M&A Advisory Report — {deal.name}",
            "",
            f"**Client:** {deal.client_name}",
            f"**Deal Type:** {deal.deal_type or 'N/A'}",
            f"**Deal Value:** {deal.deal_value or 'N/A'}",
            f"**Date:** {datetime.utcnow().strftime('%B %d, %Y')}",
            "",
            "---",
            "",
        ]

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(advisory_data.get("executive_summary", "No summary available."))
        lines.append("")

        # Risk Matrix
        risk_dist = advisory_data.get("risk_distribution", {})
        if risk_dist:
            lines.append("## Risk Distribution")
            lines.append("")
            lines.append("| Risk Level | Count |")
            lines.append("|------------|-------|")
            for level in ["critical", "high", "medium", "low", "informational"]:
                count = risk_dist.get(level, 0)
                if count:
                    lines.append(f"| {level.upper()} | {count} |")
            lines.append("")

        # Deal Breakers
        deal_breakers = advisory_data.get("deal_breakers", [])
        if deal_breakers:
            lines.append("## Potential Deal-Breakers")
            lines.append("")
            for db in deal_breakers:
                lines.append(f"- **{db}**")
            lines.append("")

        # Key Risks
        key_risks = advisory_data.get("key_risks", [])
        if key_risks:
            lines.append("## Key Risks")
            lines.append("")
            for i, risk in enumerate(key_risks, 1):
                lines.append(f"{i}. {risk}")
            lines.append("")

        # Recommendations
        recommendations = advisory_data.get("recommendations", [])
        if recommendations:
            lines.append("## Recommendations")
            lines.append("")
            for rec in recommendations:
                lines.append(f"- {rec}")
            lines.append("")

        # Negotiation Points
        negotiation_points = advisory_data.get("negotiation_points", [])
        if negotiation_points:
            lines.append("## Negotiation Points")
            lines.append("")
            for point in negotiation_points:
                lines.append(f"- {point}")
            lines.append("")

        # Metrics
        lines.append("## Review Metrics")
        lines.append("")
        lines.append(f"- **Total Clauses Reviewed:** {advisory_data.get('total_clauses_reviewed', 0)}")
        override_rate = advisory_data.get("human_override_rate", 0)
        lines.append(f"- **Human Override Rate:** {override_rate:.0%}")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*This report was generated by ExecutionManager — AI-powered M&A contract review.*")

        return "\n".join(lines)

    def export_html(self, deal: Deal, advisory_data: dict) -> str:
        """Generate a styled HTML advisory document."""
        risk_dist = advisory_data.get("risk_distribution", {})
        deal_breakers = advisory_data.get("deal_breakers", [])
        key_risks = advisory_data.get("key_risks", [])
        recommendations = advisory_data.get("recommendations", [])
        negotiation_points = advisory_data.get("negotiation_points", [])

        risk_colors = {
            "critical": "#dc2626",
            "high": "#ea580c",
            "medium": "#ca8a04",
            "low": "#16a34a",
            "informational": "#6b7280",
        }

        risk_rows = ""
        for level in ["critical", "high", "medium", "low", "informational"]:
            count = risk_dist.get(level, 0)
            if count:
                color = risk_colors.get(level, "#6b7280")
                risk_rows += f'<tr><td><span style="color:{color};font-weight:bold">{level.upper()}</span></td><td>{count}</td></tr>\n'

        breakers_html = ""
        if deal_breakers:
            items = "".join(f"<li><strong>{db}</strong></li>" for db in deal_breakers)
            breakers_html = f"<h2>Potential Deal-Breakers</h2><ul>{items}</ul>"

        risks_html = ""
        if key_risks:
            items = "".join(f"<li>{r}</li>" for r in key_risks)
            risks_html = f"<h2>Key Risks</h2><ol>{items}</ol>"

        recs_html = ""
        if recommendations:
            items = "".join(f"<li>{r}</li>" for r in recommendations)
            recs_html = f"<h2>Recommendations</h2><ul>{items}</ul>"

        points_html = ""
        if negotiation_points:
            items = "".join(f"<li>{p}</li>" for p in negotiation_points)
            points_html = f"<h2>Negotiation Points</h2><ul>{items}</ul>"

        summary = advisory_data.get("executive_summary", "No summary available.")
        summary_html = summary.replace("\n", "<br>")

        override_rate = advisory_data.get("human_override_rate", 0)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>M&amp;A Advisory — {deal.name}</title>
<style>
  body {{ font-family: 'Georgia', serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.6; }}
  h1 {{ border-bottom: 3px solid #1a1a1a; padding-bottom: 10px; }}
  h2 {{ color: #333; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
  th {{ background: #f5f5f5; }}
  .meta {{ color: #666; font-size: 0.9em; }}
  .summary {{ background: #f8f9fa; padding: 20px; border-left: 4px solid #333; margin: 20px 0; }}
  ul, ol {{ padding-left: 25px; }}
  li {{ margin-bottom: 8px; }}
  .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.85em; color: #888; }}
</style>
</head>
<body>
<h1>M&amp;A Advisory Report — {deal.name}</h1>
<p class="meta">
  <strong>Client:</strong> {deal.client_name} |
  <strong>Deal Type:</strong> {deal.deal_type or 'N/A'} |
  <strong>Deal Value:</strong> {deal.deal_value or 'N/A'} |
  <strong>Date:</strong> {datetime.utcnow().strftime('%B %d, %Y')}
</p>

<h2>Executive Summary</h2>
<div class="summary">{summary_html}</div>

<h2>Risk Distribution</h2>
<table>
<tr><th>Risk Level</th><th>Count</th></tr>
{risk_rows}
</table>

{breakers_html}
{risks_html}
{recs_html}
{points_html}

<h2>Review Metrics</h2>
<ul>
  <li><strong>Total Clauses Reviewed:</strong> {advisory_data.get('total_clauses_reviewed', 0)}</li>
  <li><strong>Human Override Rate:</strong> {override_rate:.0%}</li>
</ul>

<div class="footer">
  <em>Generated by ExecutionManager — AI-powered M&amp;A contract review.</em>
</div>
</body>
</html>"""
